# Generated by Django 5.0.3 on 2024-03-23 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Arete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('ville_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aretes_entrantes', to='defi.ville')),
                ('ville_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aretes_sortantes', to='defi.ville')),
            ],
        ),
    ]
